name: Build & Push to DockerHub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Build latest
      run: docker build -t perosa/worldcapitalschatbot:latest .

    - name: Push to DockerHub
      run: docker push perosa/worldcapitalschatbot:latest
